[package]
name = "polars-php"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "0.15.2"
polars = { version = "0.51.0", features = ["lazy", "csv", "parquet", "json"] } # , "timezones"
polars-plan = { version = "0.51.0", features = ["mode", "is_between"] }

[profile.release]
strip = "debuginfo"
